project_id = "ogyiyfwzsphyvetxvqpr"

[functions.generate-contract]
verify_jwt = true

[functions.generate-promissory-note]
verify_jwt = true

[functions.trigger-webhooks]
verify_jwt = true

[functions.send-contract-notification]
verify_jwt = true

[functions.facebook-messenger-webhook]
verify_jwt = false

[functions.facebook-send-message]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.ai-property-match]
verify_jwt = true

[functions.ai-generate-description]
verify_jwt = true
